baseurl = "https://example.org/"
languageCode = "en-us"
title = "Madisa"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "MADISA"
	description = "organization with expertise in disaster risk reduction"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Madisa"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "disaster risk reduction"
		subtitle   = " Providing advocacy for vulnerable people exposed to disaster risks"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Madisa"
		description = "Madisa is a non profit organization with the main objective of disatser risk reduction."
		#buttonText  = "Find out more"


	# Service section
	[params.services]
		headline = "Variety of Services"

        [[params.services.list]]
            icon = "fas fa-users"
            title = "Team Expertise"
            description = "Network of Experts in Technology and disaster management"

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Environmental Awareness"
			description = "Environmental Awareness and advocacy for vulnerable people exposed to disaster risks  "

		[[params.services.list]]
            icon = "fas  fa-code"
            title = "Software Solutions"
            description = "Automated Platform that processes data in near real time coupled with an intutive interface that sends out alerts instantly"

        [[params.services.list]]
            icon = "fas fa-signal"
            title = "Network of Devices"
            description = "mesh network of devices collect and transmit data to be analyzed and processed in near real time"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	#[params.aside]
	#	headline = "create environmental awareness"

	#	[params.aside.button]
	#		text = "Take Action Now"
	#		#link = "//github.com/digitalcraftsman/hugo-creative-theme"


	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to collaborate with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "+250788480815"
		email = "manadisa16@hotmail.fr"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
 